Ported from bro to zeek compatibility

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -29,7 +29,7 @@ cat 1>&2 <<EOF
 Usage: $0 [OPTIONS]
 
   Plugin Options:
-    --bro-dist=DIR             Path to Bro source tree
+    --zeek-dist=DIR             Path to Bro source tree
     --install-root=DIR         Path where to install plugin into
 EOF
 
@@ -53,7 +53,7 @@ append_cache_entry () {
 
 # set defaults
 builddir=build
-brodist=`bro-config --bro_dist 2> /dev/null || (cd ../../.. && pwd)`
+zeekdist=`zeek-config --zeek_dist 2> /dev/null || (cd ../../.. && pwd)`
 installroot="default"
 CMakeCacheEntries=""
 
@@ -68,8 +68,8 @@ while [ $# -ne 0 ]; do
             usage
             ;;
 
-        --bro-dist=*)
-            brodist=`cd $optarg && pwd`
+        --zeek-dist=*)
+            zeekdist=`cd $optarg && pwd`
             ;;
 
         --install-root=*)
@@ -88,13 +88,13 @@ while [ $# -ne 0 ]; do
     shift
 done
 
-if [ ! -e "$brodist/bro-path-dev.in" ]; then
-    echo "Cannot determine Bro source directory, use --bro-dist=DIR."
+if [ ! -e "$zeekdist/zeek-path-dev.in" ]; then
+    echo "Cannot determine Bro source directory, use --zeek-dist=DIR."
     exit 1
 fi
 
-append_cache_entry BRO_DIST PATH $brodist
-append_cache_entry CMAKE_MODULE_PATH PATH $brodist/cmake
+append_cache_entry BRO_DIST PATH $zeekdist
+append_cache_entry CMAKE_MODULE_PATH PATH $zeekdist/cmake
 
 if [ "$installroot" != "default" ]; then
     mkdir -p $installroot
@@ -102,7 +102,7 @@ if [ "$installroot" != "default" ]; then
 fi
 
 echo "Build Directory        : $builddir"
-echo "Bro Source Directory   : $brodist"
+echo "Bro Source Directory   : $zeekdist"
 
 mkdir -p $builddir
 cd $builddir
